### ISSUE TITLE
Grid is broken on Firefox

### ISSUE THREAD

**Issue by Rogergonzalez21** [berserktech/berserktech.github.io#10]
![image](https://user-images.githubusercontent.com/1617177/52284169-44c34280-293a-11e9-92c9-a4419ae93339.png)

Flexbox is broken on Firefox (Tested on Firefox 64.0.2)

**Comment by aitbw** [comment]
Same issue is happening under Firefox Dev. Ed. 65.0b11

**Comment by sadasant** [comment]
Hi! this is expected, the flexbox will grow this way as we add more people :) it's not an issue, I'm sorry 😂

**Comment by sadasant** [comment]
Reopened because it can be fixed with a max-width and several media queries :)
