### ISSUE TITLE
Missing Jest and React Testing Library

### ISSUE THREAD

**Issue by castrolem** [berserktech/berserktech.github.io#14]
We have the scripts for `test` inside `package.json` but no testing library.

I would recommend using `jest` and maybe try out [react-testing-library](https://github.com/kentcdodds/react-testing-library) unless lots of people feel comfortable working with [Enzyme](https://github.com/airbnb/enzyme)

**Comment by adrianObel** [comment]
I'm down for using Jest + Enzyme
